export const DETECTOR_CONFIG = {
  recentPostsToInspect: 40,
  sameSubredditDominanceThreshold: 0.7,
  sameSubredditActivityThreshold: 0.5,
  highPostsPerDayThreshold: 8,
  veryHighPostsPerDayThreshold: 15,
  newAccountDays: 180,
  veryNewAccountDays: 3,
  lowCombinedKarmaThreshold: 100,
  veryLowCombinedKarmaThreshold: 20,
  repeatedPostWindowHours: 24,
  repeatedTitleSimilarityMin: 0.72,
  scoreThresholds: {
    low: 20,
    medium: 45,
    high: 70,
  },
  baitDetectionEnabled: false,
  baitTerms: [
    'am i the only one',
    'does anyone else',
    'unpopular opinion',
    'hot take',
    'prove me wrong',
    'change my mind',
    'everyone is wrong',
    'nobody talks about',
    'this will get downvoted',
    'why is nobody talking about',
    'is it just me',
    'seriously?',
    'literally',
    'obviously',
    'wake up',
    'you people',
    'all of you',
    'cope',
    'seethe',
    'triggered',
    'rent free',
    'bait',
    'ragebait',
    'controversial opinion',
  ],
  lowEffortTitleTerms: [
    'thoughts?',
    'why?',
    'how?',
    'wtf',
    'lol',
    'lmao',
    'this.',
    'bro',
    'bruh',
    'no way',
    'insane',
    'crazy',
    'what is happening',
  ],
} as const;

export const REDDIT_PAGE_MATCHES = [
  '*://reddit.com/*',
  '*://www.reddit.com/*',
  '*://old.reddit.com/*',
  '*://*.reddit.com/*',
];

export const REDDIT_POST_PATH_PATTERN = /^\/r\/[^/]+\/comments\/[^/]+/;
